name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, backend] 
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      # 1️⃣ Checkout del repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js 20
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build del proyecto
      - name: Build project
        run: |
          if [ "${{ matrix.project }}" == "frontend" ]; then
            npm run build -- --output-path=dist/frontend
          else
            npm run build
          fi

      # 5️⃣ Login a Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # 6️⃣ Deploy Frontend
      - name: Deploy Frontend
        if: matrix.project == 'frontend'
        uses: azure/webapps-deploy@v2
        with:
          app-name: frontend-affi
          package: ./dist/frontend

      # 7️⃣ Deploy Backend
      - name: Deploy Backend
        if: matrix.project == 'backend'
        uses: azure/webapps-deploy@v2
        with:
          app-name: backend-affi
          package: ./
