name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  infra:
    name: Terraform Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      # 3️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      # 4️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  build-and-deploy:
    name: Build & Deploy Apps
    runs-on: ubuntu-latest
    needs: infra
    strategy:
      matrix:
        project: [frontend, backend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js 20
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build project
      - name: Build project
        run: |
          if [ "${{ matrix.project }}" == "frontend" ]; then
            # Angular 20 build
            npx ng build --configuration production --output-path=dist/frontend
          else
            # NestJS build
            npm run build
            fi

      # 5️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # 6️⃣ Prepare backend for deploy
      - name: Prepare backend for deploy
        if: matrix.project == 'backend'
        run: |
          mkdir dist-deploy
          cp -r dist/* dist-deploy/
          cp package*.json dist-deploy/
          cd dist-deploy
          npm install --production

      # 7️⃣ Prepare frontend for deploy
      - name: Prepare frontend for deploy
        if: matrix.project == 'frontend'
        run: |
          echo "Archivos en dist/frontend:"
          ls -la dist/frontend
          mkdir dist-front
          cp -r dist/frontend/* dist-front/

      # 8️⃣ Deploy Backend
      - name: Deploy Backend
        if: matrix.project == 'backend'
        uses: azure/webapps-deploy@v2
        with:
          app-name: backend-affi-64376
          package: ./dist-deploy

      # 9️⃣ Deploy Frontend
      - name: Deploy Frontend
        if: matrix.project == 'frontend'
        uses: azure/webapps-deploy@v2
        with:
          app-name: frontend-affi-64376
          package: dist-front
